### ISSUE TITLE
SetButtonCount function inoperative

### ISSUE THREAD

**Issue by jisle15064468204** [lemmingDev/ESP32-BLE-Gamepad#103]
Hi 
When i change button count the function are no work!
this is my code

void setup()
{
    BleGamepadConfiguration bleGamepadConfig;
    bleGamepadConfig.setAutoReport(false); 
    bleGamepadConfig.setButtonCount(25);
    bleGamepad.begin();              
}

No matter how I set the button, it doesn't change.  And it's always 18 buttons instead of 16!

**Comment by lemmingDev** [comment]
![image](https://user-images.githubusercontent.com/15526971/170542859-e962bc28-89b7-44a9-bc52-0dc3f66cddeb.png)

Start with one of the updated examples...

Also, the extra 2 buttons are because the additional explicit HID select and start are enabled by default in this new version of the library, so you need to set them to false to disable. I might set them to disabled by default in the future

Try this code
```
#include <Arduino.h>
#include <BleGamepad.h>

BleGamepad bleGamepad;

void setup()
{
    BleGamepadConfiguration bleGamepadConfig;
    bleGamepadConfig.setAutoReport(false);
    bleGamepadConfig.setButtonCount(5);           // Set to the number of buttons you want
    bleGamepadConfig.setWhichSpecialButtons(false, false, false, false, false, false, false, false);  // Disable Select and Start buttons
    bleGamepad.begin(&bleGamepadConfig);          // New for this version of the library
}

void loop()
{
    if (bleGamepad.isConnected())
    {
    }
}
```

As you can see, I set 5 buttons, and only 5 buttons are enabled
![image](https://user-images.githubusercontent.com/15526971/170546906-79e2264c-9d57-4fcc-9740-3a3944488838.png)

**Comment by jisle15064468204** [comment]
Thank you very much.

**Comment by lov7777** [comment]
Hi beautiful girl and we hope you’re beautiful sexy people and love
